language: go
go:
  - 1.12.x
go_import_path: zgo.at/goatecounter
env:
  - GO111MODULE=on
notifications:
  email: false
script: |
  go test -race \
    -coverprofile=coverage.txt \
    -coverpkg=./... \
    ./...
  bash <(curl -s https://codecov.io/bash)
