language: go
os: ['linux', 'osx', 'windows']
go: ['1.14.x']
services: ['postgresql']
# GoatCounter.com actually runs on 12.2, but this is the latest version that
# seems easily installable on Travis.
addons:
  postgresql: '10'
go_import_path: 'zgo.at/goatcounter'
env: ['GO111MODULE=on']
cache:
  directories:
    - '$GOCACHE'
notifications:
  email: false

before_cache:
  # Don't cache the log file and downloads.
  - 'rm -rf $GOCACHE/log.txt $GOPATH/pkg/mod/cache/vcs'

script:
  - 'go run ./cmd/check ./...'
  - 'go test -race -timeout=3m ./...'
  - '[ "$TRAVIS_OS_NAME" = "linux" ] && go test -tags=testpg -race -timeout=3m ./... || true'
  # For some reason this doesn't work well on Windows:
  #     gofmt: exit status 2: ./pack/pack.go:15:6: unknown escape sequence
  #     ./pack/pack.go:15:14: unknown escape sequence
  #     ./pack/pack.go:24:6: unknown escape sequence
  #     ./pack/pack.go:24:14: unknown escape sequence
  #     [.. loads more ..]
  # But the resulting file looks okay if I "head -n100" it?
  # - 'go generate ./... && [ $(git status -s | wc -l) -gt 1 ] && git diff && exit 1 || true'
