#!/bin/sh
# mick-image: go

e=0
set -x

go run ./cmd/check ./...                    || e=1
go test -race -timeout=3m ./...             || e=1
go test -race -timeout=3m -tags pgsql ./... || e=1

# Make sure it at least compiles on macOS, Windows, and arm64
trap 'rm goatcounter goatcounter.exe' EXIT
GOOS=darwin  go build ./cmd/goatcounter || e=1
GOOS=windows go build ./cmd/goatcounter || e=1
GOARCH=arm64 go build ./cmd/goatcounter || e=1

exit $e
