alter table sites drop column plan;
alter table sites drop column plan_pending;
alter table sites drop column plan_cancel_at;
alter table sites drop column stripe;
alter table sites drop column billing_amount;
alter table sites drop column billing_anchor;
alter table sites drop column notes;
alter table sites drop column extra_pageviews;
alter table sites drop column extra_pageviews_sub;
